CONFIG_LOG=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_PROMPT_UART="argisense:~$ "
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_SHELL_STACK_SIZE=4096
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_EEPROM=y
CONFIG_EEPROM_AT24=y
CONFIG_DAC=y
CONFIG_DAC_GP8302=y
CONFIG_SPI=y
CONFIG_ADC=y
CONFIG_SENSOR=y
CONFIG_MS5803_05BA=y
CONFIG_DYNAMENT_PLATINUM_HYDROCARBON=y
CONFIG_ARGISENSE_HTU21D=y
CONFIG_MODBUS=y
CONFIG_MODBUS_ROLE_SERVER=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_SETTINGS_NVS_SECTOR_COUNT=8
CONFIG_REBOOT=y
CONFIG_PM=y
CONFIG_PM_DEVICE=y
CONFIG_PM_DEVICE_SYSTEM_MANAGED=y
CONFIG_PM_NEED_ALL_DEVICES_IDLE=y
CONFIG_TICKLESS_KERNEL=y
