/*
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ARGISENSE_DRIVERS_SENSOR_DYNAMENT_PLATINUM_H_
#define ARGISENSE_DRIVERS_SENSOR_DYNAMENT_PLATINUM_H_

#include <zephyr/drivers/sensor.h>

enum argisense_dynament_sensor_channel {
	ARGISENSE_DYNAMENT_SENSOR_CHAN_GAS_PPM =
		SENSOR_CHAN_PRIV_START,
	ARGISENSE_DYNAMENT_SENSOR_CHAN_GAS_PERCENT_VOLUME,
	ARGISENSE_DYNAMENT_SENSOR_CHAN_STATUS_FLAGS,
	ARGISENSE_DYNAMENT_SENSOR_CHAN_PROTOCOL_VERSION,
};

#endif /* ARGISENSE_DRIVERS_SENSOR_DYNAMENT_PLATINUM_H_ */
