/*
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ARGISENSE_DRIVERS_SENSOR_MS5803_05BA_H_
#define ARGISENSE_DRIVERS_SENSOR_MS5803_05BA_H_

#include <zephyr/drivers/sensor.h>

enum argisense_ms5803_sensor_channel {
	ARGISENSE_MS5803_SENSOR_CHAN_D1_RAW = SENSOR_CHAN_PRIV_START + 16,
	ARGISENSE_MS5803_SENSOR_CHAN_D2_RAW,
	ARGISENSE_MS5803_SENSOR_CHAN_PROM_CRC_READ,
	ARGISENSE_MS5803_SENSOR_CHAN_PROM_CRC_CALC,
};

#endif /* ARGISENSE_DRIVERS_SENSOR_MS5803_05BA_H_ */
